### ISSUE TITLE
DQMCoreTool does not compile under g++-4.7/4.8

### ISSUE THREAD

**Issue by ebrianne** [DQM4HEP/DQMCore#3]
One gets this error during compilation :

[ 19%] Building CXX object source/CMakeFiles/DQMCore.dir/src/DQMCoreTool.cc.o

> /home/calice/DQM4HEP-AHCAL/DQMCore/source/src/DQMCoreTool.cc: In static member function ‘static void dqm4hep::DQMCoreTool::sleep(const DQMTimeDuration&)’:
> /home/calice/DQM4HEP-AHCAL/DQMCore/source/src/DQMCoreTool.cc:73:2: error: ‘sleep_for’ is not a member of ‘std::this_thread’
> source/CMakeFiles/DQMCore.dir/build.make:382: recipe for target 'source/CMakeFiles/DQMCore.dir/src/DQMCoreTool.cc.o' failed
> make[5]: **\* [source/CMakeFiles/DQMCore.dir/src/DQMCoreTool.cc.o] Error 1
> CMakeFiles/Makefile2:1238: recipe for target 'source/CMakeFiles/DQMCore.dir/all' failed
> make[4]: **\* [source/CMakeFiles/DQMCore.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make[3]: **\* [all] Error 2
> CMakeFiles/DQMCore.dir/build.make:113: recipe for target 'DQMCore/src/DQMCore-stamp/DQMCore-build' failed
> make[2]: **\* [DQMCore/src/DQMCore-stamp/DQMCore-build] Error 2
> CMakeFiles/Makefile2:579: recipe for target 'CMakeFiles/DQMCore.dir/all' failed
> make[1]: **\* [CMakeFiles/DQMCore.dir/all] Error 2
> Makefile:94: recipe for target 'all' failed
> make: **\* [all] Error 2

The issue seems to be g++4.7/4.8 that is not enable by default libstdcxx-time (not enabled by default in Ubuntu 16.04 LTS g++ package). The issue seems to be solved if one goes to higher version of g++ (g++-5 works fine). 

One possible fix would be to add #define _GLIBCXX_USE_NANOSLEEP 1 in the top of DQMCoreTool include file.

---------------------------- g++ 4.7 thread -----------------------------------
# ifdef _GLIBCXX_USE_NANOSLEEP

```
/// sleep_for
template<typename _Rep, typename _Period>
  inline void
  sleep_for(const chrono::duration<_Rep, _Period>& __rtime)
  {
chrono::seconds __s =
  chrono::duration_cast<chrono::seconds>(__rtime);

chrono::nanoseconds __ns =
  chrono::duration_cast<chrono::nanoseconds>(__rtime - __s);

__gthread_time_t __ts =
  {
    static_cast<std::time_t>(__s.count()),
    static_cast<long>(__ns.count())
  };

::nanosleep(&__ts, 0);
  }

/// sleep_until
template<typename _Clock, typename _Duration>
  inline void
  sleep_until(const chrono::time_point<_Clock, _Duration>& __atime)
  { sleep_for(__atime - _Clock::now()); }
```
# endif

-------------------------------- g++ 5.3.1 thread -----------------------------------

void
    __sleep_for(chrono::seconds, chrono::nanoseconds);

```
/// sleep_for
template<typename _Rep, typename _Period>
  inline void
  sleep_for(const chrono::duration<_Rep, _Period>& __rtime)
  {
if (__rtime <= __rtime.zero())
  return;
auto __s = chrono::duration_cast<chrono::seconds>(__rtime);
auto __ns = chrono::duration_cast<chrono::nanoseconds>(__rtime - __s);
```
# ifdef _GLIBCXX_USE_NANOSLEEP

```
__gthread_time_t __ts =
  {
    static_cast<std::time_t>(__s.count()),
    static_cast<long>(__ns.count())
  };
::nanosleep(&__ts, 0);
```
# else

```
__sleep_for(__s, __ns);
```
# endif

```
  }
```

**Comment by rete** [comment]
Hi.

Thanks for reporting this bug ! I will investigate this in the next few days and come back to you. If you need it very soon, then patch it and submit a pull request. I will merge the diff the package. Let me know in this case.

Regards
